/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/*import DAO.PatientDao;
import DAO.VaccineDao;
*/
import java.awt.event.KeyEvent;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;

import java.util.List;
import javax.swing.JOptionPane;
import model.Patient;
import model.Vaccine;
import org.mindrot.jbcrypt.BCrypt;
import service.PatientInterface;
import service.VaccineInterface;

/**
 *
 * @author Mugisha
 */
public final class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        adddose();
         addvacine();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        radioGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        goToDashBoard = new javax.swing.JButton();
        IdTxt = new javax.swing.JTextField();
        FnameTxt = new javax.swing.JTextField();
        LnameTxt = new javax.swing.JTextField();
        AgeTxt = new javax.swing.JTextField();
        MaleTxt = new javax.swing.JRadioButton();
        FemaleTxt = new javax.swing.JRadioButton();
        VaccineTypeCombo = new javax.swing.JComboBox<>();
        DoseCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        datechooser = new com.toedter.calendar.JDateChooser();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("REGISTER PATIENT PANEL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Patient Id");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("First Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Last Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Sex");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Age");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Vaccine");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Dose");

        SaveBtn.setBackground(new java.awt.Color(204, 204, 255));
        SaveBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SaveBtn.setIcon(new javax.swing.ImageIcon("D:\\SEMESTER SIX\\Java\\MIDSEM PROJECT\\icons\\save.png")); // NOI18N
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setBackground(new java.awt.Color(204, 204, 255));
        UpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateBtn.setIcon(new javax.swing.ImageIcon("D:\\SEMESTER SIX\\Java\\MIDSEM PROJECT\\update.png")); // NOI18N
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        goToDashBoard.setBackground(new java.awt.Color(204, 204, 255));
        goToDashBoard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        goToDashBoard.setIcon(new javax.swing.ImageIcon("D:\\SEMESTER SIX\\Java\\MIDSEM PROJECT\\icons\\dash.png")); // NOI18N
        goToDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToDashBoardActionPerformed(evt);
            }
        });

        IdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTxtActionPerformed(evt);
            }
        });
        IdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IdTxtKeyPressed(evt);
            }
        });

        radioGroup.add(MaleTxt);
        MaleTxt.setText("Male");
        MaleTxt.setName("male"); // NOI18N

        radioGroup.add(FemaleTxt);
        FemaleTxt.setText("Female");
        FemaleTxt.setName("female"); // NOI18N

        VaccineTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaccineTypeComboActionPerformed(evt);
            }
        });

        DoseCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Date Vaccinated ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("DashBoard");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("SAVE");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("UPDATE");

        refreshBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mugisha\\Downloads\\icons8-refresh-50.png")); // NOI18N
        refreshBtn.setToolTipText("");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("REFRESH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel13)))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MaleTxt)
                        .addGap(18, 18, 18)
                        .addComponent(FemaleTxt))
                    .addComponent(AgeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(VaccineTypeCombo, 0, 143, Short.MAX_VALUE)
                    .addComponent(DoseCombo, 0, 143, Short.MAX_VALUE)
                    .addComponent(datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(goToDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(goToDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaleTxt)
                            .addComponent(FemaleTxt)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(AgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(VaccineTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(DoseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(refreshBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(SaveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        
        
        //VALIDATIONS--Empty fields
        if(IdTxt.getText().trim().isEmpty()||FnameTxt.getText().trim().isEmpty()||LnameTxt.getText().trim().isEmpty()||
           AgeTxt.getText().trim().isEmpty()||VaccineTypeCombo.getSelectedItem().toString().trim().isEmpty()  ||
                DoseCombo.getSelectedItem().toString().trim().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please provide data");
                }else{
            int Age=Integer.parseInt(AgeTxt.getText());
            int id=Integer.parseInt(IdTxt.getText());
            if(Age>=5&&id>=2){
             try{
                int idtxt=Integer.parseInt(IdTxt.getText());
            //Setting values to Model object
                Patient pat=new Patient();
                Vaccine vac=new Vaccine();
             //   vac.setVaccine_id(VaccineTypeCombo.getSelectedItem().toString());
                pat.setPatient_id(idtxt);
                pat.setFname(FnameTxt.getText());
                pat.setLname(LnameTxt.getText());
                pat.setSex(checkgender());
                pat.setAge(AgeTxt.getText());
                pat.setVaccine(VaccineTypeCombo.getSelectedItem().toString());
                pat.setDose(DoseCombo.getSelectedItem().toString());
                String dateString = datechooser.getDate().toString();
                SimpleDateFormat inputFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy");
                SimpleDateFormat outputFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date date = inputFormat.parse(dateString);
                String formattedDate = outputFormat.format(date);
                pat.setDate(formattedDate);
             
                //SENDING DATA FROM MODEL TO  to SERVICE INTERFACE 
            
                Registry registry=LocateRegistry.getRegistry("127.0.0.1",6000);
                PatientInterface service=(PatientInterface) registry.lookup("patient");
                VaccineInterface serice=(VaccineInterface) registry.lookup("vaccine");
                serice.saveVaccines(vac);
                 boolean iterator=service.isSavedId(pat);
                if(iterator){
                JOptionPane.showMessageDialog(this, "ID  "+IdTxt.getText()+" EXISTS IN DB");
                }else{
                 String feedback=service.savePatient(pat);
                 JOptionPane.showMessageDialog(this, feedback);
                }
                
                 
               
            }catch(Exception ex){
            ex.printStackTrace();
            }
            }else{
            JOptionPane.showMessageDialog(this, "check age and ID");
            }
            
            
           
            
            
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void goToDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToDashBoardActionPerformed
        // TODO add your handling code here:
        dispose();
        DashBoard dash=new DashBoard();
        dash.setVisible(true);
    }//GEN-LAST:event_goToDashBoardActionPerformed

    private void IdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTxtActionPerformed

  public  void addvacine(){
      
    try{
        VaccineTypeCombo.removeAllItems();
       
        Registry registry=LocateRegistry.getRegistry("127.0.0.1",6000);
        VaccineInterface service=(VaccineInterface) registry.lookup("vaccine");
        
        List<Vaccine> list=service.retrieveVaccines();
        Iterator iterator=list.iterator();
        
        
        //VaccineTypeCombo.addItem("--");
        while(iterator.hasNext()){
         Vaccine vac=(Vaccine) iterator.next();
         VaccineTypeCombo.addItem(vac.getVac_name());
         
        }
        
        
       /*if(list!=null){
        
            for(Vaccine vac:list){
            VaccineTypeCombo.addItem(vac.getVac_name());
            }
            
        }*/
        
        
        
        
    }catch(Exception ex){
    ex.printStackTrace();
    }
       
    }
   
   private  void adddose(){
    DoseCombo.addItem("1");
    DoseCombo.addItem("2");
    DoseCombo.addItem("3");
     
    }
    private void VaccineTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaccineTypeComboActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_VaccineTypeComboActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
 //VALIDATIONS--Empty fields
        if(IdTxt.getText().trim().isEmpty()||FnameTxt.getText().trim().isEmpty()||LnameTxt.getText().trim().isEmpty()||
           AgeTxt.getText().trim().isEmpty()||VaccineTypeCombo.getSelectedItem().toString().trim().isEmpty()  ||
                DoseCombo.getSelectedItem().toString().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide data");
                }else{
            try{
            int idtxt=Integer.parseInt(IdTxt.getText());
            //Passing values to Model object
                Patient pat=new Patient();
                pat.setPatient_id(idtxt);
                pat.setFname(FnameTxt.getText());
                pat.setLname(LnameTxt.getText());
                pat.setSex(checkgender());
                pat.setAge(AgeTxt.getText());
                pat.setVaccine(VaccineTypeCombo.getSelectedItem().toString());
                pat.setDose(DoseCombo.getSelectedItem().toString());
                pat.setDate(datechooser.getDate().toString());
             //Passing SENDING DATA FROM MODEL TO  to DAO object
            
                Registry registry=LocateRegistry.getRegistry("127.0.0.1",6000);
                PatientInterface service=(PatientInterface) registry.lookup("patient");
                
                String feedback=service.updatePatient(pat);
                JOptionPane.showMessageDialog(this, feedback);
            }catch(Exception ex){
            ex.printStackTrace();
            }
            //Passing values to Model object
            
            //setting textfields to blank
            refreshBtnActionPerformed(evt);
        }
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void IdTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdTxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try {
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 6000);
            PatientInterface service = (PatientInterface) registry.lookup("patient");

            int id = Integer.parseInt(IdTxt.getText());

            Patient pat = new Patient();
            pat.setPatient_id(id);

            Patient patt = (Patient) service.searchById(pat);

            if (patt != null) {
                FnameTxt.setText(patt.getFname());
                LnameTxt.setText(patt.getLname());
                String genderValue = patt.getSex();
                if (genderValue.equals("Male")) {
                    MaleTxt.setSelected(true);
                } else if (genderValue.equals("Female")){
                    FemaleTxt.setSelected(true);
                }
                AgeTxt.setText(patt.getAge());
                VaccineTypeCombo.setSelectedItem(patt.getVaccine());
                DoseCombo.setSelectedItem(patt.getDose());
                String dateString = patt.getDate();
                SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date date = inputFormat.parse(dateString);
                datechooser.setDate(date);
        
            } else {
                
                JOptionPane.showMessageDialog(this, "Not found");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
        
    }//GEN-LAST:event_IdTxtKeyPressed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
         IdTxt.setText("");
            FnameTxt.setText("");
            LnameTxt.setText("");
            //MaleTxt.setText(null);
            //FemaleTxt.setText(null);
            AgeTxt.setText(null);
           VaccineTypeCombo.setSelectedItem("");
           DoseCombo.setSelectedItem("");
           //calender.setDate(null);
        
    }//GEN-LAST:event_refreshBtnActionPerformed
private String checkgender(){
String selectedGender="";
            if(MaleTxt.isSelected()){
            selectedGender="Male";
            }else{
            selectedGender="Female";
            }
            return selectedGender;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JComboBox<String> DoseCombo;
    private javax.swing.JRadioButton FemaleTxt;
    private javax.swing.JTextField FnameTxt;
    private javax.swing.JTextField IdTxt;
    private javax.swing.JTextField LnameTxt;
    private javax.swing.JRadioButton MaleTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JComboBox<String> VaccineTypeCombo;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JButton goToDashBoard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
