/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Vaccine;
import service.VaccineInterface;

/**
 *
 * @author Mugisha
 */
public class SaveVaccine extends javax.swing.JFrame {
DefaultTableModel tbmodel=new DefaultTableModel();
    /**
     * Creates new form SaveVaccine
     */
    public SaveVaccine() {
        initComponents();
        addColumns();
        addrows();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vacName = new javax.swing.JTextField();
        vacId = new javax.swing.JTextField();
        saveBtnVac = new javax.swing.JButton();
        updateBtnVac = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewVaccineTable = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        txtDelete = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        datechooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        refreshBtn = new javax.swing.JButton();
        goToDashBoard = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("REGISTER VACCINE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("VAC_ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("VAC_NAME");

        saveBtnVac.setText("SAVE");
        saveBtnVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnVacActionPerformed(evt);
            }
        });

        updateBtnVac.setText("UPDATE");
        updateBtnVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnVacActionPerformed(evt);
            }
        });

        viewVaccineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        viewVaccineTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewVaccineTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewVaccineTable);

        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        txtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DATE ADDED ON");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Search");

        SearchBtn.setText("SEARCH");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("REFRESH");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        goToDashBoard.setBackground(new java.awt.Color(204, 204, 255));
        goToDashBoard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        goToDashBoard.setIcon(new javax.swing.ImageIcon("D:\\SEMESTER SIX\\Java\\MIDSEM PROJECT\\icons\\dash.png")); // NOI18N
        goToDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToDashBoardActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Back to DashBoard");

        printBtn.setText("PRINT");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(saveBtnVac)
                                        .addGap(52, 52, 52)
                                        .addComponent(updateBtnVac)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(vacId, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(vacName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                            .addComponent(txtDelete))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deleteBtn)
                                            .addComponent(SearchBtn)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(printBtn))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(4, 4, 4)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refreshBtn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(goToDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vacId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SearchBtn)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vacName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBtnVac)
                            .addComponent(saveBtnVac)
                            .addComponent(refreshBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printBtn)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(goToDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(33, 33, 33))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addColumns(){
    tbmodel.addColumn("VAC ID");
    tbmodel.addColumn("VAC NAME");
    tbmodel.addColumn("REGISTERED DATE");
    viewVaccineTable.setModel(tbmodel);
    }
    private void addrows(){
        
    try{
    
        Registry registry=LocateRegistry.getRegistry("127.0.0.1",6000);
        VaccineInterface service=(VaccineInterface) registry.lookup("vaccine");
        List<Vaccine>vacList=service.retrieveVaccines();
        
        for(Vaccine vac:vacList){
         tbmodel.addRow(new Object[]{
         vac.getVaccine_id(),
            vac.getVac_name(),
            vac.getDate()
        });
        }viewVaccineTable.setModel(tbmodel);
        
        
        
        
        
        
    }catch(Exception ex){
    ex.printStackTrace();
    }
        
        
        
        
    }
    
    
    private void saveBtnVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnVacActionPerformed
        // TODO add your handling code here:
//        VALIDATIONS ON EMPTY TEXTFILEDS
if(vacId.getText().trim().isEmpty()||vacName.getText().trim().isEmpty()||
        datechooser.getDate().toString().isEmpty()
        ){
    JOptionPane.showMessageDialog(this, "Please Enter data");
}else{
//    getting data from gui to model
   try{
              int idtxt=Integer.parseInt(vacId.getText());
              
              Vaccine vac=new Vaccine();
                
              vac.setVaccine_id(idtxt);
              vac.setVac_name(vacName.getText());
              vac.setDate(datechooser.getDate().toString());

              Registry registry = LocateRegistry.getRegistry("127.0.0.1",6000);
              VaccineInterface service = (VaccineInterface)registry.lookup("vaccine");
                 
              if(service.vaccineIsSaved(vac)){
              JOptionPane.showMessageDialog(this, "Vaccine exists");
              }else{
              String feedback=service.saveVaccines(vac);
              JOptionPane.showMessageDialog(this,feedback,"INFORMATION",JOptionPane.INFORMATION_MESSAGE);
              }
              
              
    
                  //refreshBtnActionPerformed(evt);
   
   }catch(Exception ex){ 
       ex.printStackTrace();
   }
    
    
}
        
        
        
    }//GEN-LAST:event_saveBtnVacActionPerformed

    private void updateBtnVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnVacActionPerformed
       //Empty textfields validations
        if(vacId.getText().trim().isEmpty()||vacName.getText().trim().isEmpty()||
        datechooser.getDate().toString().isEmpty()
        ){
    JOptionPane.showMessageDialog(this, "Please Enter data");
}else{
        try{
              int idtxt=Integer.parseInt(vacId.getText());
              
              Vaccine vac=new Vaccine();
                
              vac.setVaccine_id(idtxt);
              vac.setVac_name(vacName.getText());
              vac.setDate(datechooser.getDate().toString());

              Registry registry = LocateRegistry.getRegistry("127.0.0.1",6000);
              VaccineInterface service = (VaccineInterface)registry.lookup("vaccine");
                 
              String feedback=service.updateVaccines(vac);
              JOptionPane.showMessageDialog(this,feedback,"INFORMATION",JOptionPane.INFORMATION_MESSAGE);
    
                  refreshBtnActionPerformed(evt);
   
   }catch(Exception ex){ 
       ex.printStackTrace();
   }
            
            
            refreshBtnActionPerformed(evt);
        }
        
    }//GEN-LAST:event_updateBtnVacActionPerformed

    private void viewVaccineTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewVaccineTableMouseClicked
        // TODO add your handling code here:
        
        int selectedrow=viewVaccineTable.getSelectedRow();
        txtDelete.setText(tbmodel.getValueAt(selectedrow, 0).toString());
    }//GEN-LAST:event_viewVaccineTableMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        //Empty textfields validations
        if(txtDelete.getText().trim().isEmpty()
        ){
    JOptionPane.showMessageDialog(this, "Please Enter data");
}else{
            
            int choice= JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?","Delete",JOptionPane.YES_NO_OPTION);
            
             if(choice==JOptionPane.YES_OPTION){
             
             try{
             
                 int idtxt=Integer.parseInt(txtDelete.getText());
              
              Vaccine vac=new Vaccine();
                
              vac.setVaccine_id(idtxt);
              

              Registry registry = LocateRegistry.getRegistry("127.0.0.1",6000);
              VaccineInterface service = (VaccineInterface)registry.lookup("vaccine");
                 
              String feedback=service.deleteVaccines(vac);
              JOptionPane.showMessageDialog(this,feedback,"INFORMATION",JOptionPane.INFORMATION_MESSAGE);
              refreshBtnActionPerformed(evt);
             
             }catch(Exception ex){
             ex.printStackTrace();
             }
              refreshBtnActionPerformed(evt);
             }else{
              refreshBtnActionPerformed(evt);
             }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
      
        try{
      
        int id=Integer.parseInt(txtsearch.getText());
        
        Vaccine vac=new Vaccine();
        vac.setVaccine_id(id);
        
        Registry registry=LocateRegistry.getRegistry("127.0.0.1",6000);
        VaccineInterface service=(VaccineInterface) registry.lookup("vaccine");
        Vaccine vc=service.searchbyId(vac);
      tbmodel.setRowCount(0);
      viewVaccineTable.removeAll();
      tbmodel.addRow(new Object[]{
      vc.getVaccine_id(),
      vc.getVac_name(),
      vc.getDate()
     });
       viewVaccineTable.setModel(tbmodel);
       // refreshBtnActionPerformed(evt);
            
        }catch(Exception ex){
        ex.printStackTrace();
        }
       // refreshBtnActionPerformed(evt);
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
    tbmodel.setRowCount(0);
    viewVaccineTable.removeAll();
    addrows();
    vacId.setText("");
    vacName.setText("");
    txtDelete.setText("");
    txtsearch.setText("");
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void goToDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToDashBoardActionPerformed
        // TODO add your handling code here:
        dispose();
        DashBoard dash=new DashBoard();
        dash.setVisible(true);
    }//GEN-LAST:event_goToDashBoardActionPerformed

    private void txtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
       try{
       viewVaccineTable.print();
       }catch(Exception ex){
       ex.printStackTrace();
       }
    }//GEN-LAST:event_printBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaveVaccine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchBtn;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton goToDashBoard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton saveBtnVac;
    private javax.swing.JTextField txtDelete;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JButton updateBtnVac;
    private javax.swing.JTextField vacId;
    private javax.swing.JTextField vacName;
    private javax.swing.JTable viewVaccineTable;
    // End of variables declaration//GEN-END:variables
}
